services:
  - name: backend
    image: ./main
    ports:
      - port: 8000
        expose: true
    scale:
      units: 1
    env:
      - name: ENV
        value: "production"
    routes:
      - path: /
        port: 8000